//
//  Constants.swift
//  AofX
//  Copyright © 2020 Aesthet(X). All rights reserved.
//

import Foundation
import UIKit

struct Colors {
    static let aXGreen = UIColor(red: 186/255, green: 248/255, blue: 51/255, alpha: 1)
    static let aXPink = UIColor(red: 255/255, green: 191/255, blue: 247/255, alpha: 1)
    static let aXOrange = UIColor(red: 255/255, green: 191/255, blue: 0/255, alpha: 1)
    
}

struct Save {
    
//Volume Tracker vars
    static let firstBoot = "firstBoot"
    static let muscle                      = "muscle"
    static let chestTally                  = "chesttally"
    static let chestProgress               = "chestprogress"
    static let chestMax                    = "chestmax"
    static let chest                                = "chest"
    static let bicepsTally                 = "bicepstally"
    static let bicepsProgress              = "bicepsprogress"
    static let bicepsMax                   = "bicepsmax"
    static let biceps                      = "biceps"
    static let latsTally                   = "latstally"
    static let latsProgress                = "latsprogress"
    static let latsMax                     = "latsmax"
    static let lats                        = "lats"
    static let glutesTally                 = "glutestally"
    static let glutesProgress              = "glutesprogress"
    static let glutesMax                   = "glutesmax"
    static let glutes                      = "glutes"
    static let gluteMediusTally            = "glutemediustally"
    static let gluteMediusProgress         = "glutemediusprogress"
    static let gluteMediusMax              = "glutemediusmax"
    static let gluteMedius                 = "glutemedius"
    static let hamstringsTally             = "hamstringstally"
    static let hamstringsProgress          = "hamstringsprogress"
    static let hamstringsMax               = "hamstringsmax"
    static let hamstrings                  = "hamstrings"
    static let frontShoulderTally          = "frontshouldertally"
    static let frontShoulderProgress       = "frontshoulderprogress"
    static let frontShoulderMax            = "frontshouldermax"
    static let frontShoulder               = "frontshoulder"
    static let lateralShoulderTally        = "lateralshouldertally"
    static let lateralShoulderProgress     = "lateralshoulderprogress"
    static let lateralShoulderMax          = "lateralshouldermax"
    static let lateralShoulder             = "lateralshoulder"
    static let backShoulderTally           = "backshouldertally"
    static let backShoulderProgress        = "backshoulderprogress"
    static let backShoulderMax             = "backshouldermax"
    static let backShoulder                = "backshoulder"
    static let rotatorCuffTally            = "rotatorCufftally"
    static let rotatorCuffProgress         = "rotatorCuffprogress"
    static let rotatorCuffMax              = "rotatorCuffmax"
    static let rotatorCuff                 = "rotatorCuff"
    static let quadsTally                  = "quadstally"
    static let quadsProgress               = "quadsprogress"
    static let quadsMax                    = "quadsmax"
    static let quads                       = "quads"
    static let absTally                    = "abstally"
    static let absProgress                 = "absprogress"
    static let absMax                      = "absmax"
    static let abs                         = "abs"
    static let obliquesTally               = "obliquestally"
    static let obliquesProgress            = "obliquesprogress"
    static let obliquesMax                 = "obliquesmax"
    static let obliques                    = "obliques"
    static let serratusTally               = "serratustally"
    static let serratusProgress            = "serratusprogress"
    static let serratusMax                 = "serratusmax"
    static let serratus                    = "serratus"
    static let transverseAbTally           = "transverseabtally"
    static let transverseAbProgress        = "transverseabprogress"
    static let transverseAbMax             = "transverseabmax"
    static let transverseAb                = "transverseab"
    static let calvesTally                 = "calvestally"
    static let calvesProgress              = "calvesprogress"
    static let calvesMax                   = "calvesmax"
    static let calves                      = "calves"
    static let neckTally                   = "necktally"
    static let neckProgress                = "neckprogress"
    static let neckMax                     = "neckmax"
    static let neck                        = "neck"
    static let forearmExtensorsTally       = "forearmextensorstally"
    static let forearmExtensorsProgress    = "forearmextensorsprogress"
    static let forearmExtensorsMax         = "forearmextensorsmax"
    static let forearmExtensor             = "forearmextensor"
    static let ulnarForearmTally           = "ulnarforearmtally"
    static let ulnarForearmProgress        = "ulnarforearmprogress"
    static let ulnarForearmMax             = "ulnarforearmmax"
    static let ulnarForearm                = "ulnarforearm"
    static let forearmFlexorsTally         = "forearmflexorstally"
    static let forearmFlexorsProgress      = "forearmflexorsprogress"
    static let forearmFlexorsMax           = "forearmflexorsmax"
    static let forearmFlexors              = "forearmflexors"
    static let radialForearmTally          = "radialforearmtally"
    static let radialForearmProgress       = "radialforearmprogress"
    static let radialForearmMax            = "radialforearmmax"
    static let radialForearm               = "radialForearm"
    static let spinalErectorsTally         = "spinalerectorstally"
    static let spinalErectorsProgress      = "spinalerectorsprogress"
    static let spinalErectorsMax           = "spinalerectorsmax"
    static let spinalErector               = "spinalerector"
    static let upperTrapsTally             = "uppertrapstally"
    static let upperTrapsProgress          = "uppertrapsprogress"
    static let upperTrapsMax               = "uppertrapsmax"
    static let upperTrap                   = "uppertraps"
    static let lowerTrapsTally             = "lowertrapstally"
    static let lowerTrapsProgress          = "lowertrapsprogress"
    static let lowerTrapsMax               = "lowertrapsmax"
    static let lowerTraps                  = "lowertraps"
    static let tricepsTally                = "tricepstally"
    static let tricepsProgress             = "tricepsprogress"
    static let tricepsMax                  = "tricepsmax"
    static let triceps                     = "triceps"
    static let formExercise                = "formExercise"
    static let annualPurchased             = "annual"
    static let monthlyPurchased            = "monthly"
    static let biannualPurchased           = "biannual"
    static let volumeTxts                  = "volumeTxts"
    static let repsTxts                      = "repstxts"
    static let weightTxts                  = "weighttxts"
    static let dateHist                      = "datehist"
    static let exTitleHist                          = "extitlehist"
    static let setsTxts                                            = "setstxts"
    static let  RPETxts                         = "RPETxts"
    static let  noteTxts                         = "noteTxts"
    
    //Integers to apply the math on to HS progress bars.
    
    static let chestProgressInt            = "chestProgressInt"
    static let bicepsProgressInt           = "bicepsProgressInt"
    static let latsProgressInt             = "latsProgressInt"
    static let glutesProgressInt           = "glutesProgressInt"
    static let gluteMediusProgressInt      = "gluteMediusProgressInt"
    static let hamstringsProgressInt       = "hamstringsProgressInt"
    static let frontShoulderProgressInt    = "frontShoulderProgressInt"
    static let lateralShoulderProgressInt  = "lateralShoulderProgressInt"
    static let backShoulderProgressInt     = "backShoulderProgressInt"
    static let rotatorCuffProgressInt     = "roatatorCuffProgressInt"
    static let quadsProgressInt            = "quadsProgressInt"
    static let absProgressInt              = "absProgressInt"
    static let obliquesProgressInt         = "obliquesProgressInt"
    static let serratusProgressInt         = "serratusProgressInt"
    static let transverseAbProgressInt     = "transverseAbProgressInt"
    static let tricepsProgressInt          = "tricepsProgressInt"
    static let calvesProgressInt           = "calvesProgressInt"
    static let neckProgressInt             = "neckProgressInt"
    static let forearmExtensorsProgressInt  = "forearmExtensorProgressInt"
    static let ulnarForearmProgressInt     = "ulnarForearmProgressInt"
    static let forearmFlexorsProgressInt    = "forearmFlexorProgressInt"
    static let radialForearmProgressInt    = "radialForearmProgressInt"
    static let spinalErectorsProgressInt    = "spinalErectorProgressInt"
    static let upperTrapsProgressInt       = "upperTrapsProgressInt"
    static let lowerTrapsProgressInt       = "lowerTrapsProgressInt"
    static let muscleString                = "musclestring"
    
    //Payment options
    static let showFab                     = "showFab"
    static let run                         = "run"
    static let HSPromo                      = "hspromo"
    static let promoLength                      = "promolength"
    static let installDate                     = "installdate"
    static let firstTime                   = "firsttime"
    static let  premium                     = "premium"
    
    //Dashbaord vars
    
    static let bodyWeight            = "bodyweight"
    static let heightBig             = "heightbig"
    static let heightSmall           = "heightsmall"
    static let experience            = "experience"
    static let composition           = "composition"
    static let age                   = "age"
    static let sex                   = "sex"
    static let activityLevel         = "activitylevel"
    static let totalMuscleGrowth     = "totalmusclegrowth"
    static let idealBodyWeight       = "idealbodyweight"
    static let fatLoss               = "fatloss"
    static let currentMuscleGrowth   = "currentmusclegrowth"
    static let potentialMuscleGrowth = "potentialmusclegrowth"
    static let muscleGrowthRate      = "musclegrowthrate"
    static let dailyCaloricDeviance  = "dailycaloricdeviance"
    static let unitsBool             = "unitsBool"
    static let infoTapped            = "infotapped"
    
    //Meal Plan Vars
 
    static let fat                   = "fat"
    static let carbs                 = "carbs"
    static let protein               = "protein"
    static let sbprogress            = "sbprogress"
    static let probprogress          = "probprogress"
    static let calsbprogress         = "calsbprogress"
    static let deficit               = "deficit"
    static let calories              = "calories"
    static let intake                = "intake"
    static let tdee                  = "tdee"
    static let maxlossrate           = "maxlossrate"
    static let minlossrate           = "minlossrate"
    static let maxFatIntake          = "maxfatintake"
    static let calSeekBarPosition    = "calSeekBarPosition"
    static let fatDistance           = "fatDistance"
    static let lbm                   = "lbm"
    static let cseekBarPosition      = "seekbarposition"
    static let fatSB                 = "fatSB"
    static let calPosition           = "calposition"
    static let proSBProgress         = "proSBProgress"
    static let proSeekBarPostion     = "proSeekBarPostion"
    static let fatSBPosition         = "fatSBPosition"
    static let energySeekBarPosition = "energySeekBarPosition"
    static let proteinSeekBarPosition = "proteinSeekBarPosition"
    static let volumeAD = "ca-app-pub-3950672419252348/8930486777"
    
    //History Vars

    static let muscleHistoryString             = "musclehistorystring"
    static let exerciseTitle          = "exercisetitle"
       // .rpeTxts
  
    
}
